# Generated by Django 4.2.6 on 2023-11-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('entregado', 'Entregado')], default='solicitado', max_length=20),
        ),
    ]
